### ISSUE TITLE
Integrate Google Map with Google Places

### ISSUE THREAD

**Issue by josalmi** [TheSoftwareFactory/lokki-android#102]
https://developers.google.com/places/

**Comment by ffagerho** [comment]
Addressed in #298.

**Comment by Grandi** [comment]
What is the thing that is still wanted to be implemented? At least searching places and auto-completion were added last week.

**Comment by ffagerho** [comment]
I think the search and auto-completion features are enough to fulfil this.

**Comment by Grandi** [comment]
Okay, I'll close this then.
