### ISSUE TITLE
Fix places screen UI

### ISSUE THREAD

**Issue by chums923** [TheSoftwareFactory/lokki-android#123]

**Comment by chums923** [comment]
(1) Long press on any of the places should allow the user to re-order the places. 
(2) Need to figure out a more intuitive way of deleting (long pressing the name isn't a long term solution).
Doing both of the above while still preserving the swipe to see all contacts in the place is going to require one more level of control in the page. Maybe an edit button?

**Comment by josalmi** [comment]
Also if name is one or two characters long you can't remove the place :)

**Comment by chums923** [comment]
Also for some reason, scrolling on the places screen does not work for me. Like scrolling down if you have more than 5 places

**Comment by josalmi** [comment]
If you start working on this you might want to know that backend actually limits places max count to 5 :( We should probably discuss if such limit is necessary.

**Comment by eemihauk** [comment]
You could look into using the new [Lollipop CardView](http://www.google.com/design/spec/components/cards.html#) to create a modern listing of places as in [this picture](http://material-design.storage.googleapis.com/publish/v_2/material_ext_publish/0Bx4BSt6jniD7b2tsZndLZC01a1k/components_cards8.png). I personally would like a layout similar to this.

**Comment by vforteli** [comment]
I think one thing to consider here is; how many places would the average user have? 2? 5? 50?

That would definitely be awesome for 2 – 10 maybe. Probably not for 50 ^^

**Comment by rayfarias56** [comment]
I was thinking about continuing forward with a listview and using a bottom sheet to relay actions after a long press. 

http://www.google.com/design/spec/components/bottom-sheets.html

**Comment by vforteli** [comment]
Well that would definitely make more sense than how it works now

**Comment by rayfarias56** [comment]
About to craft a pull request for some of the changes I have. I would need the 5 places limit to be removed in order to investigate the "lack of scrolling" bug. Reorder and Rename or going to be two features I'll add in later.
