### ISSUE TITLE
Update user instructions

### ISSUE THREAD

**Issue by ffagerho** [TheSoftwareFactory/lokki-android#154]

**Comment by chums923** [comment]
Example: update the instructions on the places page to reflect the new UI on the map. There's also a typo in there :p. If we get enough of these ideas written down to make it worth it, we can submit a pull request

**Comment by Kapoor-uh** [comment]
Corrected some typo's

**Comment by Kapoor-uh** [comment]
Please comment guys if u find more options which need to be updated in user instruction

**Comment by newa34** [comment]
No more typo error.
