### ISSUE TITLE
Create places mocks

### ISSUE THREAD

**Issue by rayfarias56** [TheSoftwareFactory/lokki-android#174]
creating mocks for the concepts Alex and I thought of and one using cards. Should be done in a couple days and links will be posted in the Google Group

**Comment by rayfarias56** [comment]
https://docs.google.com/drawings/d/1B4-Fy1YeIDskFqm_B2zB3oegvCQRTxhRDorrei2qDk8/edit?usp=sharing

**Comment by Kauhsa** [comment]
Wee, looks good! If these are two different options, personally I think I'd lean towards the second one – if we ever need any more actions, they can be easily added to the menu and editing the name using tiny field at the bottom left of the item is going to look a bit odd.

Cards vs. lists... I don't know. If Google tells us to use list for homogeneous content, maybe that's we should use – it seems to make sense anyway if going with concept two.

But this is just how I feel. Any other opinions?
