### ISSUE TITLE
Delete a place by long pressing place image, not text

### ISSUE THREAD

**Issue by eemihauk** [TheSoftwareFactory/lokki-android#21]
If the place text is small, it is not intuitive to the user to long press the text.

**Comment by vforteli** [comment]
With Androids new material design swiping the place to the right to delete would probably make more sense

**Comment by vforteli** [comment]
Sliding to delete introduces one problem. Currently contacts in places are placed inside the listitem. If they overflow the contacts will scroll to the side. This will perhaps conflict with swiping to delete

**Comment by chums923** [comment]
We definitely can't do swipe to delete if we are swiping to see more contacts. But we could maybe use long-press as a right click (also in Android UI design patterns) which would open up a pop-up that allows edit/delete. We could also do long-press + scroll to re-order the page
