### ISSUE TITLE
When adding your own email as a contact, app notifies that the addition succeeded

### ISSUE THREAD

**Issue by eemihauk** [TheSoftwareFactory/lokki-android#22]
You are not actually added to your own contacts, but the notification is erroneous.

**Comment by Kauhsa** [comment]
This is not only when you're adding your own email as a contact. If you select no-one at all, it also happily lets you to click "add contacts" button and tell that your location is now shared.

This probably requires many refinements:

1. Disable "add contacts" button when you have no-one selected.
2. Disable search box and show a message "no contacts" when the contact list is empty. Currently the UI is *very* confusing if you don't happen to have any contacts.
3. Actually react to errors from backend – it's not letting these kind of contact additions through and tells you about it, but Android client doesn't currently seem to care.

**Comment by DocV** [comment]
This seems to be fixed in #312 and #315
