### ISSUE TITLE
Fix unchecked casts

### ISSUE THREAD

**Issue by Grandi** [TheSoftwareFactory/lokki-android#275]
The build gives a lot of warnings about unchecked casts (e.q. http://sf-8.cs.helsinki.fi:8080/job/lokki-android-pr/161/console). The best option would be to check them somehow, but according to some googlying it might be impossible in most of the cases. One option could be just to suppress them with @SuppressWarnings("unchecked") if they can't be fixed.

**Comment by ffagerho** [comment]
In cases where fixing is possible with reasonable effort, just go ahead and fix. If the unchecked cast seems reasonably safe, go ahead and add `@SuppressWarnings` annotations. For the rest, it's probably better to leave them alone for now.
