### ISSUE TITLE
 Map loads on default mode after restarting 

### ISSUE THREAD

**Issue by newa34** [TheSoftwareFactory/lokki-android#288]
Selecting Map mode other than default get effective but on next restart map is loaded on default mode even though setting has other mode selected.

**Comment by zoeszhen** [comment]
When the application have sign out function, the problem solved already.

**Comment by ffagerho** [comment]
See #41.

**Comment by zoeszhen** [comment]
Seems I misunderstood this issue. I think the problem still exist.
