### ISSUE TITLE
Add some kind of hint to the add places interface so users know they can pan and zoom

### ISSUE THREAD

**Issue by zoeszhen** [TheSoftwareFactory/lokki-android#289]
When users want to pin the location on the map, the application always give too big size of the circle

**Comment by eemihauk** [comment]
You can adjust the size of the place by zooming the map while the place is being created (the circle of the place has a dashed outline). If this was what you were talking about...

**Comment by ffagerho** [comment]
Perhaps we could try adding some kind of hint to the user so they know they can pan and zoom the map while adding a place.

**Comment by zoeszhen** [comment]
Thats the problem I am talking about. I think we should give some hint maybe inside the circle so that user knows how to use it.
