### ISSUE TITLE
After adding a contact, contact is not shown in the contact list

### ISSUE THREAD

**Issue by eemihauk** [TheSoftwareFactory/lokki-android#29]

**Comment by Kauhsa** [comment]
So as far as I know, only Eemi's phone shows this behaviour – anyone else able to reproduce?

**Comment by vforteli** [comment]
Nope, havent seen this bug

**Comment by vforteli** [comment]
I have managed to "replicate" this now by accident. Also Akiras phone seems to have the same issue
