### ISSUE TITLE
Move contacts to server

### ISSUE THREAD

**Issue by DocV** [TheSoftwareFactory/lokki-android#291]
Contacts are currently stored on the user's device, which means that they're shared between all accounts on the same phone and will not be carried over if the user switches to a new device.
Contacts (and any other user-specific data that might currently be stored in the app) should be stored on the server instead.

**Comment by ffagerho** [comment]
We should discuss about the contacts in general and whether it would make sense to integrate with the android contacts (or whatever it's called).

**Comment by ffagerho** [comment]
The app and server need to be able to synchronise their contacts. Names and other information come from the local contacts on the phone.

**Comment by DocV** [comment]
Things I've figured out about this so far:
https://docs.google.com/document/d/1yoh_0ey9jhLFVerATzoxcbAgE7Dr3AmEEHtBYmXFMaM/edit#
