### ISSUE TITLE
assigning names to email contacts

### ISSUE THREAD

**Issue by soumyaijteee** [TheSoftwareFactory/lokki-android#297]
I have given the app link to few users and the feedback is we cannot assign names to contact.
Probably that is one of the basic feature we can work on

**Comment by newa34** [comment]
The contact name is assign if the contact is on the Phone's contact list. So, it is again about storing or not contacts on Lokki server.

**Comment by ffagerho** [comment]
Yes, we should consider how to handle contacts altogether. The current way may not be the best.

**Comment by ffagerho** [comment]
I'm closing this because names work in the right way already. Once #291 is done, the contacts work like they should.
