### ISSUE TITLE
Add a search panel to the main map interface where the user can search for a place

### ISSUE THREAD

**Issue by soumyaijteee** [TheSoftwareFactory/lokki-android#298]
Its a problem when you have to mark a new place on the map because you have to navigate to the point , where it would be better if we could search a place by its name in the map

**Comment by ffagerho** [comment]
Is this a duplicate of #301?

**Comment by ffagerho** [comment]
At least this is a duplicate of #27 :).

**Comment by iatarah** [comment]
assigning this to Antti, seem to be more challenging than i thought
