### ISSUE TITLE
Add Buzz feature

### ISSUE THREAD

**Issue by ffagerho** [TheSoftwareFactory/lokki-android#308]
The buzz feature allows the user to set a buzz alarm for a place. When the device enters the place, the app buzzes to notify the user.

The user can also optionally add a separate buzz radius to the place. That radius takes precedence when buzzing. The separate radius is not shown on the map but is just a distance that the user can enter using numbers, a slider, or some other input method.

DoD:
- feature code completed
- automated tests completed
- analytics integration completed
- code reviewed :)

**Comment by Kapoor-uh** [comment]
Added Buzz feature,Automated test etc. but couldn't test vibration feature on emulator
