### ISSUE TITLE
Add a hint for first-time users that lets them know how to add places on the map

### ISSUE THREAD

**Issue by ffagerho** [TheSoftwareFactory/lokki-android#320]
The hint is displayed until the user has added a place. The hint reappears if the user has no places.

**Comment by Grandi** [comment]
I was implementing this into the Map View fragment, but noticed that empty Places fragment already informs the user about how to add places on map. I don't think that the same tip needs to be in multiple parts of the application, but of course if the original tip is thought to be too hidden, I can continue working on this issue and plant it into Map View fragment like I intended to.

**Comment by ffagerho** [comment]
I think new users may not discover the hint in the Places fragment. Since the app opens in the Map view, displaying the hint there will ensure first-time users see it. Once they've added a Place, the hint in the Places fragment is probably enough. So I'd suggest continuing.

**Comment by Grandi** [comment]
Done.
