### ISSUE TITLE
Make tests do proper clean up

### ISSUE THREAD

**Issue by DocV** [TheSoftwareFactory/lokki-android#347]
Some tests like the AddContactsScreenTests don't seem to properly reset the application state afterwards, which can cause some tests to succeed when they are run individually but fail when all tests are run at once.

**Comment by Grandi** [comment]
Could you give little more details of what you mean? The tests do succeed even when they are run all at once. Or are you referring to the flakiness?

**Comment by DocV** [comment]
The AddContactsScreen tests set custom display names for the default test contacts (family.member@example.com etc.), but don't remove them afterwards. The contacts and search screens will display the custom names if they exist or the email otherwise, so if you (for example) make a test where you search for "family.member@example.com" and then check that a search result with the text "family.member@example.com" is visible, it will succeed when run individually, but fail when running all tests, because then the display text will be "Family Member" instead.
