### ISSUE TITLE
Ignore excess whitespace in place names

### ISSUE THREAD

**Issue by Grandi** [TheSoftwareFactory/lokki-android#351]
You cannot have two places with the same name, but you can have place names "X" and "X " which will look exactly the same. Also, the client attempts to turn the place names into form `uppercase(first character) + lowercase(rest of the name)`, but if the name begins with whitespace, it's going to be completely lowercase. In fact, you can even add places whose names are nothing but whitespace.

**Comment by DocV** [comment]
This should be easily fixable with String.trim()

**Comment by iatarah** [comment]
Done!
