### ISSUE TITLE
Add a notification to confirm account

### ISSUE THREAD

**Issue by DocV** [TheSoftwareFactory/lokki-android#368]
As per https://github.com/TheSoftwareFactory/lokki-server/issues/66 the server should delete new accounts after 24 hours if they're not confirmed. New users should receive some notification of this when they first log in, otherwise they may inadvertently lose data if they don't happen to check their mail within 24 hours.

**Comment by ffagerho** [comment]
The signup procedure should be tried to confirm it works as it is supposed to.
