### ISSUE TITLE
Decrease battery consumption

### ISSUE THREAD

**Issue by vforteli** [TheSoftwareFactory/lokki-android#37]
Currently Lokki seems to be quite a heavy battery user. Perhaps possible to optimize by using newer APIs?

**Comment by eemihauk** [comment]
Removed "bug" label because this doesn't really break anything.

**Comment by ffagerho** [comment]
This could be turned into a milestone because it likely needs several subtasks to get a measure of current battery consumption, specific enhancement tasks to change the code, and testing tasks to see if there was any improvement.

**Comment by vforteli** [comment]
Actually, I dont know if this is a coincidence, or maybe we have changed something along the line, because the app doesnt appear that high in the list at least on my phone anymore
