### ISSUE TITLE
App starts FirstTimeActivity when opened after being suspended for a long time

### ISSUE THREAD

**Issue by DocV** [TheSoftwareFactory/lokki-android#384]
If let the app stay suspended for a while an then reopen it, it will launch FirstTimeActivity even if the terms of use have already been accepted. You may also have to click through FirstTimeActivity several times before the map screen appears. Manually closing the app prevents this from happening.

**Comment by ffagerho** [comment]
We believe 76f86d4 fixes this, but it is nearly impossible to verify. We will reopen this bug if this issue persists.
