### ISSUE TITLE
Automatically disable Log statements in production builds

### ISSUE THREAD

**Issue by ffagerho** [TheSoftwareFactory/lokki-android#393]
Calls to android.util.Log.* should not be included in production builds. At the moment, we comment out the calls manually in the release branch. A better way is described here: http://stackoverflow.com/a/2466662

DoD: Log statements are automatically disabled in production builds.

**Comment by olzraiti** [comment]
74bb5ddc5cb6f4644ff5704dd6c17b0bf5590592 closes this

**Comment by ffagerho** [comment]
This was fixed by https://github.com/TheSoftwareFactory/lokki-android/pull/400
