### ISSUE TITLE
Renaming and deleting contacts is not working

### ISSUE THREAD

**Issue by akkashaider** [TheSoftwareFactory/lokki-android#435]
1. Go to contact screen, try to rename or delete contact.
2. It does not work.
3. Following error is shown in logcat.
E/ServerApi: Error fetching contacts: -103 - transform error.
4. If you reopen contacts it is renamed or deleted, but it should be renamed first time

**Comment by olzraiti** [comment]
I can't reproduce this. I tried with an account I created before API v2 was introduced and also with a new account. I wonder if your account is in a buggy state?

**Comment by akkashaider** [comment]
It is not being reproduced right now. Going to close it now, we can reopen it happens again.
