### ISSUE TITLE
Should show user location on map (Offline)

### ISSUE THREAD

**Issue by bwadjass** [TheSoftwareFactory/lokki-android#458]
Check if the accurate location will  be shown to the user based on GPS (offline),  If there is no internet connection.

**Comment by ffagerho** [comment]
Let's do two things at this point:
1. If the device has no network connection, display an "offline" icon in the top bar.
2. If the device has no network connection, disable actions that require network communication, e.g. add place, and show a notification dialog if the user tries to use those actions.
