### ISSUE TITLE
If email confirmation need to be send during registration, registration button doesn't work anymore

### ISSUE THREAD

**Issue by Kauhsa** [TheSoftwareFactory/lokki-android#55]

**Comment by zkgan** [comment]
Signup button gets stuck at "Signing up..", and cannot be clicked.

**Comment by vforteli** [comment]
I havent verified this, but is this by design? I think it seemed like it sits there waiting for the user to verify the email, and then continue automatically?

**Comment by Kauhsa** [comment]
Good point – though, even if that's the case, the UI could be more informative, especially since the authorization email is not guaranteed to arrive anytime soon (or even be shown on users device; email account is not necessarily connected to the device in any way).

**Comment by josalmi** [comment]
#129 fixed this
